### PR TITLE
Fixing vulnerabilities

### PR DESCRIPTION
**Pull request by sullof**
Fixes many vulnerabilities found by npm during the install.

### CODE REVIEW

**Comment by D-Nice** [comment]
On my Linux machine, upon which I have to delete the lock files for both branches, you branch appears to introduce more vulnerable packages, with one considered high, while master only has low.

fix-vulnerabilities:
found 559 vulnerabilities (553 low, 5 moderate, 1 high)

master: 
found 544 low severity vulnerabilities

SS:
image

**Comment by D-Nice** [comment]
Also have you been able to get the bridge working with your branch, it would not even start for me due to bitcore-lib issue, but that could very well be since i had to clear the lock files.

I have followed some of your changes, and vulnerabilities should be brought down to 2 low, and the bridge should thereafter be installable without the lockfiles even, at least until the dependencies using bitcore don't increment the minor versioning or they drop the version guard.

**Comment by D-Nice** [comment]
If you have time to let me know whether the following branch achieves what you were looking for, I'll see to push it through after testing on some other OS's as well: https://github.com/oraclize/ethereum-bridge/tree/fix-vulns

**Comment by sullof** [comment]
@D-Nice 
I used npm audit fix after installing all the packages. For me, on OSX, it worked pretty well, eliminating all the vulnerabilities. Also, I used it intensively for tests without any issue.
But, I didn't try on Linux. I guess that there it requires a different auditing process because many of the vulnerabilities are related to the specific OS.
I will try your branch and let you know asap. In the mean time you can close this PR.

**Comment by sullof** [comment]
@D-Nice 
I cloned the branch and installed the dependences, and I had this:
```
added 476 packages from 480 contributors and audited 9069 packages in 15.369s
found 559 vulnerabilities (553 low, 5 moderate, 1 high)
```

**Comment by D-Nice** [comment]
thanks i'll give it a try on OSX and see if results are different. Did you make sure you checked out to `fix-vulns` branch, I made that mistake with your fork, failing to change branch, and it seems to match master result.

**Comment by D-Nice** [comment]
as an update, I retried your fork, with the correct branch and got 4 low vulns. I've integrated changes similar to yours and dropped some dependencies no longer needed for fixing a previous dep issue, and that one is down to 2 low vulns. I will try later on OSX/Windows, which should attain the same.

**Comment by D-Nice** [comment]
Closing this PR, thanks for the help @sullof

**Pull request closed without merging**
